import Airtable from 'airtable';

export function getAirtableBase() {
  const apiKey = process.env.AIRTABLE_API_KEY;
  const baseId = process.env.AIRTABLE_BASE_ID;
  if (!apiKey || !baseId) {
    throw new Error('Airtable API Key or Base ID is missing from environment variables');
  }
  return new Airtable({ apiKey }).base(baseId);
}

// Table IDs fetched via Metadata API
export const TABLES = {
  STORYTELLERS: 'tbl9zxLsGOd3fjWXp',
  MEDIA: 'tbldCVl8n3JyPvamD',
  THEMES: 'tblbfySNA6wg9lR12',
  QUOTES: 'tblCq6v5eQl3GNkBO',
  GALLERIES: 'tbl6YnHXjnPMC6ENx',
  STORIES: 'tbl34r8BqNDgPI3ZN',
  SHIFTS: 'tblArZd2LG32otN1A',
  MANUAL_TAGS: 'tblSKRtr1wAYilVMJ',
  COMMENTS: 'tblMtUK5zvDYL5drk',
  CONTACT: 'tblCAr2KCgtFi0y1M',
  USERS: 'tblMMHSiT7awfSjOR',
  ASSIGNMENT_TABLE: 'tblZB2qXlhGhu8jSI',
  POST_SHIFT_REFLECTION: 'tblu1gdJgiUtc8ZZN',
  PHOTOGRAPHER_THEMES: 'tblAZnGkFw5EtXIq7',
  FORMS: 'tblRwVbSL4vOsJkrw',
  EMPATHY_JOURNAL: 'tblTyQF7nVTX14GpE',
} as const;

// Field names for each table
export const FIELDS = {
  STORYTELLERS: {
    NAME: 'Name',
    SUMMARY_FROM_MEDIA: 'Summary (from Media)',
    THEMES_FROM_MEDIA: 'Themes (from Media)',
    DESCRIPTION_FROM_THEMES_FROM_MEDIA: 'Description (from Themes) (from Media)',
    QUOTES_FROM_MEDIA: 'Quotes (from Media)',
    THEME_FROM_QUOTES_FROM_MEDIA: 'Theme (from Quotes) (from Media)',
    TRANSCRIPT_FROM_MEDIA: 'Transcript (from Media)',
    PROJECT: 'Project',
    PROJECT_FROM_MEDIA: 'Project (from Media)',
    FILE_PROFILE_IMAGE: 'File Profile Image',
    LOCATION: 'Location',
    ROLE: 'Role',
    ORGANISATION: 'Organisation',
    DONE: 'Done',
    MEDIA: 'Media',
    SECURE_CONTACT_EMAIL: 'Secure Contact Email',
    PREFERENCES: 'Preferences',
    CREATED_AT: 'Created At',
    FILE_PATH_URL_FROM_MEDIA: 'File Path/URL (from Media)',
    MAGIC_LINK_URL: 'Magic Link URL',
    USER_ROLE: 'User Role',
    UNIQUE_STORYTELLER_ID: 'Unique Storyteller ID',
    CONSENT_STATUS: 'Consent Status',
    PREFERRED_ANONYMITY_LEVEL: 'Preferred Anonymity Level',
    LAST_UPDATED_BY_STORYTELLER: 'Last Updated By Storyteller',
    PREFERRED_NAME: 'Preferred Name',
    PHONE_NUMBER: 'Phone Number',
    COMMENTS: 'Comments',
    CONSENT_FORM_PHOTO: 'Consent Form Photo',
    SIGNATURE: 'Signature',
    LOCATION_ROLLUP_FROM_MEDIA: 'Location Rollup (from Media)',
    TAG: 'Tag',
    VIDEO_DRAFT_LINK_ROLLUP_FROM_MEDIA: 'Video draft link Rollup (from Media)',
    CREATED: 'Created',
    VIDEO_DRAFT_LINK_FROM_MEDIA: 'Video draft link (from Media)',
    RAW_VIDEO_AND_PHOTO_URL: 'RAW Video and photo URL',
    USER_WHO_ADDED_STORY: 'User who added story',
    VIDEO_DRAFT_LINK_FROM_MEDIA_2: 'Video draft link (from Media) 2',
    GALLERIES_FROM_MEDIA: 'Galleries (from Media)',
    LINK_FROM_GALLERIES_FROM_MEDIA: 'Link (from Galleries) (from Media)',
    STORIES_FROM_MEDIA: 'Stories (from Media)',
    SHIFTS_FROM_MEDIA: 'Shifts (from Media)',
  },
  MEDIA: {
    FILE_NAME: 'File Name',
    STORYTELLERS: 'Storytellers',
    TRANSCRIPT: 'Transcript',
    SUMMARY: 'Summary',
    THEMES: 'Themes',
    DESCRIPTION_FROM_THEMES: 'Description (from Themes)',
    QUOTES: 'Quotes',
    THEME_FROM_QUOTES: 'Theme (from Quotes)',
    LOCATION: 'Location',
    PROJECT: 'Project',
    SHIFTS: 'Shifts',
    VIDEO_DRAFT_LINK: 'Video draft link',
    CREATED_AT: 'Created At',
    TYPE: 'Type',
    PROCESSED: 'Processed',
    GALLERIES: 'Galleries',
    AUDIO: 'Audio',
    STORIES: 'Stories',
    DROPBOX: 'Dropbox',
    FILE_PROFILE_IMAGE_FROM_STORYTELLERS: 'File Profile Image (from Storytellers)',
    LINK_FROM_GALLERIES: 'Link (from Galleries)',
    POST_SHIFT_REFLECTION: 'Post-Shift Reflection',
    ASSIGNEE_FROM_POST_SHIFT_REFLECTION: 'Assignee (from Post-Shift Reflection)',
    REFLECTION_TRANSCRIPT_FROM_POST_SHIFT_REFLECTION:
      'Reflection Transcript (from Post-Shift Reflection)',
  },
  THEMES: {
    THEME_NAME: 'Theme Name',
    DESCRIPTION: 'Description',
    STORYTELLERS_ROLLUP_FROM_RELATED_MEDIA: 'Storytellers Rollup (from Related Media)',
    RELATED_MEDIA: 'Related Media',
    QUOTES_FROM_RELATED_MEDIA: 'Quotes (from Related Media)',
  },
  QUOTES: {
    QUOTE_TEXT: 'Quote Text',
    TRANSCRIPT_REFERENCE: 'Transcript Reference',
    THEME: 'Theme',
  },
  GALLERIES: {
    GALLERY_NAME: 'Gallery Name',
    SHOOT_DATE: 'Shoot Date',
    LINK: 'Link',
    GALLERY_TYPE: 'Gallery Type',
    MEDIA: 'Media',
    STORYTELLERS_FROM_MEDIA: 'Storytellers (from Media)',
    SHIFTS_FROM_MEDIA: 'Shifts (from Media)',
    STORIES_FROM_MEDIA: 'Stories (from Media)',
    STORYTELLERS: 'Storytellers',
  },
  STORIES: {
    STORY_ID: 'Story ID',
    SHIFTS_FROM_MEDIA: 'Shifts (from Media)',
    SHIFTS: 'Shifts',
    GEOCACHE_FROM_SHIFTS: 'Geocache (from Shifts)',
    LOCATION_FROM_MEDIA: 'Location (from Media)',
    STATE_FROM_SHIFTS: 'State (from Shifts)',
    STORYTELLERS_FROM_MEDIA: 'Storytellers (from Media)',
    VIDEO_EMBED_CODE: 'Video Embed Code',
    TITLE: 'Title',
    FILE_PROFILE_IMAGE_FROM_STORYTELLERS_FROM_MEDIA:
      'File Profile Image (from Storytellers) (from Media)',
    MEDIA: 'Media',
    TRANSCRIPT_FROM_MEDIA: 'Transcript (from Media)',
    WATERMARK: 'Watermark',
    PERMISSIONS: 'Permissions',
    STORY_IMAGE: 'Story Image',
    STATUS: 'Status',
    CREATED: 'Created',
    LINK_FROM_GALLERIES_FROM_MEDIA: 'Link (from Galleries) (from Media)',
    VIDEO_STORY_LINK: 'Video Story Link',
    STORY_TRANSCRIPT: 'Story Transcript',
    STORY_COPY: 'Story copy',
    TOTAL_USES: 'Total Uses',
    USAGE_LOGS: 'Usage Logs',
    STORYTELLERS: 'Storytellers',
  },
  SHIFTS: {
    NAME: 'Name',
    DATE: 'Date',
    DAY: 'Day',
    ADDRESS: 'Address',
    STATE: 'State',
    GEOCACHE: 'Geocache',
    CONTACT_PERSON: 'Contact Person',
    CONTACT_PERSON_EMAIL: 'Contact Person Email',
    CONTACT_PERSON_PHONE_NUMBER: 'Contact Person Phone Number',
    STATUS: 'Status',
    NOTES: 'Notes',
    ASSIGNMENT_TABLE: 'Assignment Table',
    POST_SHIFT_REFLECTION: 'Post-Shift Reflection',
    GALLERIES: 'Galleries',
    MEDIA: 'Media',
    STORYTELLERS_FROM_MEDIA: 'Storytellers (from Media)',
    LATITUDE: 'Latitude',
    LONGTITUDE: 'Longtitude',
    STORIES: 'Stories',
  },
  MANUAL_TAGS: {
    TAG_NAME: 'Tag Name',
  },
  COMMENTS: {
    COMMENT: 'Comment',
    STORYTELLER: 'Storyteller',
    UNIQUE_STORYTELLER_ID_FROM_STORYTELLER_2: 'Unique Storyteller ID (from Storyteller) 2',
    DATE: 'Date',
    ADMIN_RESPONSE: 'Admin Response',
    RESOLVED_STATUS: 'Resolved Status',
    UNIQUE_STORYTELLER_ID_FROM_STORYTELLER: 'Unique Storyteller ID (from Storyteller)',
  },
  CONTACT: {
    NAME: 'Name',
    EMAIL: 'Email',
    ASSIGNEE: 'Assignee',
    STATUS: 'Status',
    COMMENT: 'Comment',
  },
  USERS: {
    NAME: 'Name',
    EMAIL: 'Email',
    AVATAR: 'Avatar',
    CREATED_TIME: 'Created time',
    STORYTELLERS: 'Storytellers',
    BIO: 'Bio',
    PHONE: 'Phone',
    LOCATION: 'Location',
    WEBSITE: 'Website',
    ASSIGNMENT_TABLE: 'Assignment Table',
    POST_SHIFT_REFLECTION: 'Post-Shift Reflection',
    SELECT: 'Select',
  },
  ASSIGNMENT_TABLE: {
    ASSIGNMENT_ID: 'Assignment ID',
    SHIFTS: 'Shifts',
    STATE_FROM_SHIFTS: 'State (from Shifts)',
    ADDRESS_FROM_SHIFTS_2: 'Address (from Shifts) 2',
    PHOTOGRAPHER_STATUS: 'Photographer Status',
    PHOTOGRAPHER: 'Photographer',
    NOTES: 'Notes',
    DATE_FROM_SHIFTS: 'Date (from Shifts)',
    ADDRESS_FROM_SHIFTS: 'Address (from Shifts)',
    CONTACT_PERSON_FROM_SHIFTS: 'Contact Person (from Shifts)',
    DAY_ROLLUP_FROM_SHIFTS: 'Day Rollup (from Shifts)',
  },
  POST_SHIFT_REFLECTION: {
    NAME: 'Name',
    ASSIGNEE: 'Assignee',
    RATING: 'Rating',
    SHIFTS: 'Shifts',
    REFLECTION_VIDEO: 'Reflection video',
    REFLECTION_TRANSCRIPT: 'Reflection Transcript',
    PHOTOGRAPHER_THEMES: 'Photographer themes',
    CREATED: 'Created',
    NOTES: 'Notes',
    WEBHOOK_SENT: 'Webhook Sent',
    MEDIA: 'Media',
  },
  PHOTOGRAPHER_THEMES: {
    PHOTOGRAPHER_THEME_NAME: 'Photographer Theme Name',
    DESCRIPTION: 'Description',
    POST_SHIFT_REFLECTION: 'Post-Shift Reflection',
  },
  FORMS: {
    NAME: 'Name',
    STATUS: 'Status',
    ATTACHMENTS: 'Attachments',
    IMAGE: 'Image',
  },
  EMPATHY_JOURNAL: {
    ENTRY_TITLE: 'Entry Title',
    CONTENT: 'Content',
    DATE_CREATED: 'Date Created',
    AUTHOR: 'Author',
    CATEGORY: 'Category',
    WORD_COUNT: 'Word Count',
  },
} as const;

// View names
export const VIEWS = {
  STORIES: {
    PUBLISHED: 'Published',
    DRAFT: 'Draft',
    ARCHIVED: 'Archived',
  },
} as const;
